# email_sender.py
import streamlit as st
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import pandas as pd
from io import BytesIO

def send_forecast_email(to_email, forecast_df, forecast_change, target_col, horizon):
    """Send forecast report via email"""
    
    # Create email content
    subject = f"Forecast Report: {target_col} - {forecast_change:.1f}% change"
    
    # Create HTML body
    body = f"""
    <html>
    <body>
    <h2>📈 Forecast Report</h2>
    <p><strong>Target:</strong> {target_col}</p>
    <p><strong>Forecast Change:</strong> {forecast_change:.2f}% over {horizon} days</p>
    <p><strong>Next 7 days forecast:</strong></p>
    <table border="1" cellpadding="5" style="border-collapse: collapse;">
        <tr style="background-color: #f2f2f2;">
            <th>Date</th>
            <th>Forecast Value</th>
        </tr>
    """
    
    for _, row in forecast_df.head(7).iterrows():
        body += f"""
        <tr>
            <td>{row['date'].strftime('%Y-%m-%d')}</td>
            <td>{row['forecast']:.2f}</td>
        </tr>
        """
    
    body += """
    </table>
    <p><small>Generated by Auto Time-Series Forecasting App</small></p>
    </body>
    </html>
    """
    
    # For demo, just show what would be sent
    st.info(f"📧 Email would be sent to: {to_email}")
    st.markdown("---")
    st.markdown("### 📧 Email Preview:")
    st.markdown(f"**To:** {to_email}")
    st.markdown(f"**Subject:** {subject}")
    st.markdown("---")
    st.markdown(body, unsafe_allow_html=True)
    
    return True

def send_forecast_with_attachment(to_email, forecast_df, forecast_change, target_col):
    """Send email with CSV attachment"""
    
    # Create CSV
    csv_buffer = BytesIO()
    forecast_df.to_csv(csv_buffer, index=False)
    csv_buffer.seek(0)
    
    st.success(f"✅ Report ready to send to {to_email}")
    st.download_button(
        label="📎 Download CSV to attach to email",
        data=csv_buffer,
        file_name=f"forecast_{target_col}.csv",
        mime="text/csv"
    )
    
    return True